---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_h: 179
          hue_l: 0
          lightness_h: 27
          lightness_l: 0
          saturation_h: 255
          saturation_l: 159
        yellow:
          hue_h: 179
          hue_l: 0
          lightness_h: 142
          lightness_l: 53
          saturation_h: 255
          saturation_l: 206