---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_h: 139
          hue_l: 20
          lightness_h: 255
          lightness_l: 122
          saturation_h: 217
          saturation_l: 13
        yellow:
          hue_h: 126
          hue_l: 8
          lightness_h: 255
          lightness_l: 80
          saturation_h: 195
          saturation_l: 100